name: Deploy to GitHub Pages with LFS

on:
  push:
    # 同时监听 main 和 master 分支的推送
    branches: [ main, master ] 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # 开启 LFS 追踪

      - name: Force Pull LFS objects
        run: git lfs pull

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4