name: Deploy to GitHub Pages with LFS

on:
  push:
    branches: [ main ] # 如果你的主分支叫 master，请确保这里一致

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # 开启 LFS 追踪

      # 修改这里：使用 pull 代替 checkout，确保 102MB 的数据被真实拉取
      - name: Force Pull LFS objects
        run: git lfs pull

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4